### ISSUE TITLE
[JOSS Review] Missing links in Community Guidelines

### ISSUE THREAD

**Issue by molgor** [ghislainv/forestatrisk#33]
Hi @ghislainv,

I'm reviewing your software for publication in the JOSS. The journal requires instructions for collaborators and contributors detailed in a community guideline and a code of conduct.
The ´README.md´ file includes a section for these items but the links to these resources seem broken. 

Cheers,

Juan

**Comment by kbarnhart** [comment]
linking to joss-reviews/issues/2975

**Comment by ghislainv** [comment]
Thanks @molgor , this has been fixed in dca0ef8
