### ISSUE TITLE
drop gdal 

### ISSUE THREAD

**Issue by 12rambau** [ghislainv/forestatrisk#82]
As you can imagine I would like to set this as a module in SEPAL (and outside as well) but to do that I would need to drop the gdal requirements of the lib. 

I can start the modifications in a PR but i would need some support to make sure I don't break anything. 

Would you have some time for small support ?

**Comment by ghislainv** [comment]
Hi @12rambau. No problem, we can work together on that.

**Comment by ghislainv** [comment]
This project has been abandoned.
