### ISSUE TITLE
Problem with gadm3.6 access

### ISSUE THREAD

**Issue by thomasarsouze** [ghislainv/forestatrisk#87]
gadm server for `gadm3.6` seems to be down since few days (at least, I can't access it, from different locations and computers).
`gadm4.1` seems to be ok though. Any reason not to update to this version ?

https://github.com/ghislainv/forestatrisk/blob/d1c813ca95504e2f061eb62c4e758e71da8b67c7/forestatrisk/data/download/download_gadm.py#L38

**Comment by ghislainv** [comment]
@thomasarsouze Thanks for raising this issue. I have updated the code to use GADM v4.1: 5ee9e84.
